spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:test
    driverClassName: oracle.jdbc.driver.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    username: SIMANOV_AN_NEW_PHIZIC
    password: 123456
    hikari:
      connectionTimeout: 30000
      idle-timeout: 60000
      max-lifetime: 120000
      auto-commit: false
      minimum-idle: 1
      maximum-pool-size: 2
      pool-name: HikariDataSourcePool
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false