spring:
  datasource:
    url: jdbc:h2:mem:smart-mocks;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: sa
    password:
    initialization-mode: always
    platform: h2
    schema: classpath:/config/schema.sql
    data: classpath:/config/data.sql
    hikari:
      connectionTimeout: 30000
      idle-timeout: 60000
      max-lifetime: 120000
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 2
      pool-name: HikariDataSourcePool
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

