CREATE TABLE IF NOT EXISTS SMART_MOCKS
(
  ID NUMBER NOT NULL,
  UPDATE_TIME DATE NOT NULL,
  MOCK_NAME VARCHAR (256),
  REQUEST_NAME VARCHAR (256),
  REG_EXPRESSION VARCHAR (2048),
  ROLL_CHANCE NUMBER(3,0),
  RESPONSE_BODY TEXT,

  PRIMARY KEY(ID)
);
CREATE INDEX IF NOT EXISTS INDEX_SM_REQ_NAME ON SMART_MOCKS(REQUEST_NAME);

CREATE SEQUENCE IF NOT EXISTS SEQ_SM_ID start with 1 increment by 10 minvalue 1 cache 10 nocycle;
