db:
  driver: org.h2.jdbcx.JdbcDataSource
  url: jdbc:h2:C:/work/h2/mocks;DB_CLOSE_DELAY=-1;IFEXISTS=FALSE;AUTO_SERVER=FALSE;DB_CLOSE_ON_EXIT=TRUE;
  username: sa
  password:
  socket:
    timeout: 60